"""phosphor help / phosphor docs - one manual, three readers.

doc/manual/*.md is the only source. `phosphor help TOPIC` shows a page in the
terminal; `phosphor docs` builds AGENTS.md (the reference AI assistants read)
from the same pages and fills the key table from share/keys.json; `phosphor
docs --check` fails when AGENTS.md is out of date. Edit the manual, never a
copy.
"""
import json, os, re, shutil, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ui import *

MAN = os.path.join(REPO, "doc", "manual")
AGENTS = os.path.join(REPO, "AGENTS.md")
ORDER = ["concepts", "install", "patterns", "profile", "commands", "keys", "phones",
         "workspaces", "mentions", "web", "tunnels", "clipboard", "privacy", "troubleshooting"]

RULES = """# AGENTS.md — Phosphor Deck for AI assistants

GENERATED by `phosphor docs` from doc/manual/*.md. Don't edit it; edit the manual.

## Rules for assistants

- The profile (`~/.config/phosphor/deck.toml`) is the only source of truth.
  Change it (or use `phosphor setup`), then `phosphor gen && phosphor restart`.
  Never edit files marked "GENERATED BY phosphor gen".
- Prefer `phosphor` commands over hand-made zellij/systemd changes.
- Verify with `phosphor doctor`; read the logs listed in troubleshooting.
- Don't test against the live `deck` session: use a throwaway one
  (`zellij --layout L attach --create-background probe`), and never
  `zellij action new-tab` with no client attached.
- `phosphor restart` closes every pane, possibly the one you run in; from
  inside the deck it detaches itself, and every screen that came in with
  `deck` goes back in by itself.
- The chat feed is read-only: never send, reply or post on the user's behalf.
- Browser access (`phosphor web on`) publishes a terminal: only when the user
  asks, tailnet only, never `tailscale funnel`.
- Keep personal data out of the repo; run `phosphor privacy` before a push.
- Only claim what you checked: run the command, read the file.
- `share/commands.json` says which subcommands can mutate live state and
  which need the deck already running: check it before running one
  unattended, and keep it in sync (`tests/commands-manifest-check.py`)
  when a command's shape changes.


## Working on Phosphor itself

Read this before changing anything in this repository, whichever assistant
you are. The state of the work lives in the repo and in the deck's notebook,
not in any one assistant's memory.

- **Start by reading** `phosphor notes` (the latest entries say what was done
  and what's next) and the open issues. **End by leaving** a short
  `phosphor note` saying what changed and what's pending.
- **Branches:** `main` is what people run; `dev` is where work happens. Work
  in a checkout of `dev`, never in the one the live deck runs from. Never run
  a real `phosphor gen`, `up` or `restart` from a `dev` checkout: gen points the
  live deck at the code it ran from. `--dry-run` and read-only commands are fine.
- **Verify through CI, not by hand:** `sh tests/check.sh` locally (seconds),
  push `dev`, then `python3 tests/ci.py`: it waits for that commit's pipeline
  and prints one line per job, plus the end of the log of any job that failed.
  Don't poll pipelines, click through the deck or drive screens yourself to
  check a change: write the check into tests/ (a throwaway zellij for keys and
  taps, like tests/edit-check.py) and let the pipeline run it. Trying it on
  real screens is the tester's and the maintainer's part; what they find
  becomes a failing test first, then the fix.
- **Every change updates, in the same commit:** CHANGELOG.md (under
  `## Unreleased`, written for users), README.md, the manual page in
  doc/manual it touches, and AGENTS.md (`phosphor docs`). English only.
  Before closing a topic, grep the docs for the old names and behavior. The
  pipeline's docs job fails a push whose code changed without CHANGELOG.md
  (`[no-changelog]` in a commit message, for a refactor users never see).
- **Privacy:** the pre-commit hook (`phosphor privacy`) blocks IPs, users,
  emails and servers. Never commit a personal email or a real host name as an
  example; commits use the maintainer's noreply address.
- **Push named refs only** (`dev`, `main`, `vX.Y.Z`), never `--all`, `--mirror`
  or every tag: a checkout may hold local history that must stay local.
- **Open merge requests, before merging one or cutting a release:**
  `python3 tests/mrs-check.py`. The pipeline only runs on protected refs
  (main, dev, tags), on purpose: a merge request's own branch never gets
  one, so nobody's code runs on the runner before it's looked at. This is
  the stand-in -- a real merge into a throwaway worktree, nothing pushed,
  then the fast checks against the result -- so a conflict or a test that
  only breaks once it's merged shows up before it's dev's problem.
  `tests/release.py` runs it too, as a heads-up, not a blocker.
- **Open GitHub issues and PRs, same moment:** `python3 tests/github-check.py`
  (also run by `tests/release.py`, same heads-up spirit). Nothing else polls
  the public mirror -- real dev happens on GitLab, but a bug report or
  feature request only ever lands on GitHub, so this is the one place it
  gets looked at. A PR there can't be merged as-is (main is squashed and
  force-pushed at every sync): point the author at an issue instead.
- **Releases** come as topics close, without waiting to be asked: a patch
  version (0.2.26, 0.2.27...) for each closed topic or batch of fixes, and the
  next minor (0.3.0) when its roadmap milestone is covered and its bugs are
  checked. Patches stay on `dev` (the nightly channel): `main`, the stable
  channel, only moves at a minor, so users on stable never get half a
  milestone. `python3 tests/release.py X.Y.Z "title"` does a dev release from a
  dev checkout, stopping at the first problem: checks, VERSION and CHANGELOG,
  dev's pipeline, the tag, its pipeline; the pipeline's release job publishes
  the notes. Add `--main` for a minor: main is fast-forwarded on the remote
  first. A bug that hurts stable users before then is cherry-picked onto
  `main` by hand and released as a patch of that minor. It never touches the
  live deck's checkout: the brain takes the release with `phosphor update`
  (`--channel nightly` for a dev one). `tests/release.py` also syncs the
  public GitHub mirror (github.com/rsmedrano-cloud/phosphor-deck) as its
  last step: a squashed commit onto GitHub's own `main` at a minor, onto
  GitHub's own `dev` at a patch -- building on that branch's previous sync
  there (a real, if squashed, history on GitHub), never GitLab's granular
  one. Titled after the release, authored as the maintainer, no AI
  co-author. Best-effort on purpose: a GitHub hiccup there is printed, not
  fatal -- it never undoes a GitLab release that already shipped; fix by
  hand (`tests/release.py`'s own `sync_github()`, called standalone, does
  the same sync again). At a minor only, also a real GitHub Release for
  that tag, with the cross-compiled Rust binaries (`rust/fleet-poll`,
  `rust/run`; the tag's own `rust-release` CI job cross-compiles them,
  x86_64 and aarch64, with plain rustup targets) attached -- `install.sh`'s
  `fetch()` reads `releases/latest` there, and it always installs from
  `main`, so shipping this at every dev patch too would make
  `releases/latest` drift ahead of what a plain clone of `main` actually
  checks out. Same best-effort spirit (`sync_github_binaries()`), same
  standalone-rerun escape hatch. Announcing it anywhere beyond the repo
  itself (Hacker News, Reddit...) stays the maintainer's call.
- **The deck is someone's live session:** anything that restarts it, rewrites
  the profile or touches mounts gets checked before and after.
"""

def page(name):
    txt = open(os.path.join(MAN, name + ".md")).read()
    if "<!-- keys:_deck -->" in txt:
        try:
            k = json.load(open(os.path.join(REPO, "share", "keys.json")))["_deck"]["k"]
            rows = ["| key | action |", "|---|---|"] + \
                   ["| %s | %s |" % (a, b) for a, b in k if a] + [""] + [b for a, b in k if not a]
            txt = txt.replace("<!-- keys:_deck -->", "\n".join(rows))
        except Exception:
            import dlog
            dlog.event("DOCS", "keys-table-failed")   # never str(e): it can quote the install path
    return txt

def build():
    parts = [RULES] + [re.sub(r"^# ", "## ", re.sub(r"^## ", "### ", page(n), flags=re.M), flags=re.M)
                       for n in ORDER]
    return "\n".join(p.rstrip() + "\n" for p in parts)

IMG = re.compile(r"^!\[(.*?)\]\((.*?)\)$")

def render(md, w):
    out = []
    for l in md.splitlines():
        m = IMG.match(l)
        if m:
            # a screenshot: real content on GitLab/GitHub, a caption here --
            # there's no way to show the image itself in a terminal
            out.append(DIM + "  · screenshot: " + (m.group(1) or m.group(2)) + RST)
        elif l.startswith("#"):
            out.append(BLOOM + l.lstrip("# ").upper() + RST)
        elif l.startswith("    "):
            out.append(PH + l + RST)
        elif l.startswith("|"):
            cells = [c.strip() for c in l.strip("|").split("|")]
            if set("".join(cells)) <= set("-: "): continue
            out.append("  " + AMB + cells[0].ljust(18) + RST + FG + "  ".join(cells[1:]) + RST)
        else:
            l = re.sub(r"\*\*(.+?)\*\*", BLOOM + r"\1" + RST, l)
            l = re.sub(r"`([^`]+)`", PH + r"\1" + RST, l)
            out.append(l)
    return "\n".join(out) + "\n"

def help(topic):
    names = [n for n in ORDER if n.startswith(topic)] if topic else []
    if not names:
        print(render(page("README") if os.path.exists(os.path.join(MAN, "README.md")) else "", 80))
        return 0 if not topic else 1
    text = render(page(names[0]), shutil.get_terminal_size((80, 24)).columns)
    if sys.stdout.isatty() and shutil.which("less"):
        subprocess.run(["less", "-R", "-F", "-X"], input=text, text=True)
    else:
        sys.stdout.write(text)
    return 0

def docs(check=False):
    new = build()
    old = open(AGENTS).read() if os.path.exists(AGENTS) else ""
    if check:
        ok = old == new
        print(row(OK if ok else BAD, "AGENTS.md", "up to date" if ok else "out of date: run phosphor docs"))
        return 0 if ok else 1
    open(AGENTS, "w").write(new)
    print(row(OK, "AGENTS.md", "%d lines from %d pages" % (new.count("\n"), len(ORDER))))
    return 0
